version: "3.9"
services:
  api:
    build: core/.
    ports:
      - "80:80"
    restart: always
    command: gunicorn --workers=14 -b 0.0.0.0:80 -k uvicorn.workers.UvicornWorker main:app

  tarantool:
    build: database/
    ports:
      - "3301:3301"
    environment:
      - TARANTOOL_USER_NAME=admin
      - TARANTOOL_USER_PASSWORD=example
    tty: true
    restart: always